version: '2.1'

services:
  react-sample:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '4321:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - './:/opt/app'
      - '/opt/app/sample-app/node_modules'